//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSolution.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lk_AddressKeyword
    {
        public int AddressID { get; set; }
        public string AddressKeyword { get; set; }
    }
}
