//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSolution.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public int UserID { get; set; }
        public string NotificationMessage { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsDimissed { get; set; }
    }
}
