//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSolution.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string OrganizationName { get; set; }
        public int UserTypeID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> LastLogIn { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> MasterOrganization { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string BusinessNo { get; set; }
        public Nullable<bool> IsTempPassword { get; set; }
    }
}
