//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSolution.PDFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PDFService.IReportRequestService")]
    public interface IReportRequestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/RequestReportLink", ReplyAction="http://tempuri.org/IReportRequestService/RequestReportLinkResponse")]
        DataSolution.Service.PDFService.ClientRequestProcess RequestReportLink(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/RequestReportLink", ReplyAction="http://tempuri.org/IReportRequestService/RequestReportLinkResponse")]
        System.Threading.Tasks.Task<DataSolution.Service.PDFService.ClientRequestProcess> RequestReportLinkAsync(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/RequestReportBytes", ReplyAction="http://tempuri.org/IReportRequestService/RequestReportBytesResponse")]
        DataSolution.Service.PDFService.ClientRequestProcess RequestReportBytes(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/RequestReportBytes", ReplyAction="http://tempuri.org/IReportRequestService/RequestReportBytesResponse")]
        System.Threading.Tasks.Task<DataSolution.Service.PDFService.ClientRequestProcess> RequestReportBytesAsync(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/RequestHistoryList", ReplyAction="http://tempuri.org/IReportRequestService/RequestHistoryListResponse")]
        DataSolution.Service.PDFService.RequestHistory[] RequestHistoryList(string SubscriberNo, string UserEmail, string MFSecCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/RequestHistoryList", ReplyAction="http://tempuri.org/IReportRequestService/RequestHistoryListResponse")]
        System.Threading.Tasks.Task<DataSolution.Service.PDFService.RequestHistory[]> RequestHistoryListAsync(string SubscriberNo, string UserEmail, string MFSecCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/PDFReportResultProcess", ReplyAction="http://tempuri.org/IReportRequestService/PDFReportResultProcessResponse")]
        DataSolution.Service.PDFService.ClientResultProcess PDFReportResultProcess(string ReportCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportRequestService/PDFReportResultProcess", ReplyAction="http://tempuri.org/IReportRequestService/PDFReportResultProcessResponse")]
        System.Threading.Tasks.Task<DataSolution.Service.PDFService.ClientResultProcess> PDFReportResultProcessAsync(string ReportCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportRequestServiceChannel : DataSolution.PDFService.IReportRequestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportRequestServiceClient : System.ServiceModel.ClientBase<DataSolution.PDFService.IReportRequestService>, DataSolution.PDFService.IReportRequestService {
        
        public ReportRequestServiceClient() {
        }
        
        public ReportRequestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportRequestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportRequestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportRequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataSolution.Service.PDFService.ClientRequestProcess RequestReportLink(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket) {
            return base.Channel.RequestReportLink(SubscriberNo, MFSecCode, UserName, UserEmail, Ticket);
        }
        
        public System.Threading.Tasks.Task<DataSolution.Service.PDFService.ClientRequestProcess> RequestReportLinkAsync(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket) {
            return base.Channel.RequestReportLinkAsync(SubscriberNo, MFSecCode, UserName, UserEmail, Ticket);
        }
        
        public DataSolution.Service.PDFService.ClientRequestProcess RequestReportBytes(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket) {
            return base.Channel.RequestReportBytes(SubscriberNo, MFSecCode, UserName, UserEmail, Ticket);
        }
        
        public System.Threading.Tasks.Task<DataSolution.Service.PDFService.ClientRequestProcess> RequestReportBytesAsync(string SubscriberNo, string MFSecCode, string UserName, string UserEmail, string Ticket) {
            return base.Channel.RequestReportBytesAsync(SubscriberNo, MFSecCode, UserName, UserEmail, Ticket);
        }
        
        public DataSolution.Service.PDFService.RequestHistory[] RequestHistoryList(string SubscriberNo, string UserEmail, string MFSecCode) {
            return base.Channel.RequestHistoryList(SubscriberNo, UserEmail, MFSecCode);
        }
        
        public System.Threading.Tasks.Task<DataSolution.Service.PDFService.RequestHistory[]> RequestHistoryListAsync(string SubscriberNo, string UserEmail, string MFSecCode) {
            return base.Channel.RequestHistoryListAsync(SubscriberNo, UserEmail, MFSecCode);
        }
        
        public DataSolution.Service.PDFService.ClientResultProcess PDFReportResultProcess(string ReportCode) {
            return base.Channel.PDFReportResultProcess(ReportCode);
        }
        
        public System.Threading.Tasks.Task<DataSolution.Service.PDFService.ClientResultProcess> PDFReportResultProcessAsync(string ReportCode) {
            return base.Channel.PDFReportResultProcessAsync(ReportCode);
        }
    }
}
